# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_mcmcCheckConvergence_wrappers", use_symbols = TRUE, package_name = "mcmcCheckConvergence")

#' @usage NULL
#' @useDynLib mcmcCheckConvergence, .registration = TRUE
NULL

#' 计算 MCMC 链的 ESS（Geyer IPS）
ess_tracer <- function(x) .Call(wrap__ess_tracer, x)

effective_size <- function(x) .Call(wrap__effective_size, x)

tree_clades <- function(tree) .Call(wrap__tree_clades, tree)

tree_tips <- function(tree) .Call(wrap__tree_tips, tree)

clade_counts <- function(trees) .Call(wrap__clade_counts, trees)

clade_sets <- function(trees) .Call(wrap__clade_sets, trees)

clade_sets_and_counts <- function(trees) .Call(wrap__clade_sets_and_counts, trees)

align_named_vectors <- function(vec_list) .Call(wrap__align_named_vectors, vec_list)

read_trace <- function(paths, format, delim, burnin, `_check_names`, skip) .Call(wrap__read_trace, paths, format, delim, burnin, `_check_names`, skip)

load_trees <- function(file, format, gens_per_tree, trim, logfile, skip) .Call(wrap__load_trees, file, format, gens_per_tree, trim, logfile, skip)

load_multi <- function(path, tree_files, log_files, format, labels, skip) .Call(wrap__load_multi, path, tree_files, log_files, format, labels, skip)

load_files <- function(path, list_files, format, `_tree_name`) .Call(wrap__load_files, path, list_files, format, `_tree_name`)

get_info <- function(all_runs, run, names_to_exclude, trees, split_windows) .Call(wrap__get_info, all_runs, run, names_to_exclude, trees, split_windows)

remove_burnin <- function(output, burnin) .Call(wrap__remove_burnin, output, burnin)

clade_freq_named <- function(x, start, end) .Call(wrap__clade_freq_named, x, start, end)

clade_freq_tree <- function(x) .Call(wrap__clade_freq_tree, x)

clade_freq_trees <- function(x, start, end) .Call(wrap__clade_freq_trees, x, start, end)

check_clades_freq <- function(runs, freq) .Call(wrap__check_clades_freq, runs, freq)

ess_cont_param <- function(runs, windows, names_to_exclude, tracer) .Call(wrap__ess_cont_param, runs, windows, names_to_exclude, tracer)

ess_split_freq <- function(runs, tracer) .Call(wrap__ess_split_freq, runs, tracer)

split_freq <- function(runs, windows) .Call(wrap__split_freq, runs, windows)

mean_cont_param <- function(runs, names_to_exclude) .Call(wrap__mean_cont_param, runs, names_to_exclude)

ks_test <- function(runs, windows, names_to_exclude) .Call(wrap__ks_test, runs, windows, names_to_exclude)

ks_threshold <- function(alpha, ess) .Call(wrap__ks_threshold, alpha, ess)

min_ess <- function(per) .Call(wrap__min_ess, per)

expected_diff_splits <- function(ess) .Call(wrap__expected_diff_splits, ess)

se <- function(x) .Call(wrap__se, x)

quants <- function(x) .Call(wrap__quants, x)

check_convergence_r <- function(list_files, format, tracer, burnin, precision, names_to_exclude, emit_logs) .Call(wrap__check_convergence_r, list_files, format, tracer, burnin, precision, names_to_exclude, emit_logs)


# nolint end
